"""fix audit_log sequence_number to be a real identity column

The Day 1 migration declared sequence_number as autoincrement=True at the
SQLAlchemy ORM level, which only auto-populates the PRIMARY KEY column
automatically. sequence_number is a separate unique column, not the PK, so
the database was never actually told to generate it — resulting in a plain
INTEGER NOT NULL with no default, which rejects every insert with a NULL
violation. This alters it into a genuine Postgres IDENTITY column so the
database generates sequential values itself.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-01

"""
import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ADD GENERATED BY DEFAULT AS IDENTITY is safe on an existing NOT NULL
    # integer column with no rows — Postgres just starts the sequence at 1.
    # If this table already has rows when you run this in a real
    # environment, use "RESTART WITH <max+1>" after this statement instead
    # of assuming 1.
    op.execute(
        "ALTER TABLE audit_log ALTER COLUMN sequence_number "
        "ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE audit_log ALTER COLUMN sequence_number DROP IDENTITY IF EXISTS"
    )
